import { requireAdmin,adminErrorStatus,writeAdminAuditLog } from "@/lib/admin-security";
import { adminDb } from "@/lib/firebase-admin";
import { MarketplaceError,validId } from "@/lib/marketplace-server";
import { FieldValue } from "firebase-admin/firestore";
import { NextRequest,NextResponse } from "next/server";
export async function GET(request:NextRequest){try{await requireAdmin(request,"finance:read");const db=adminDb(),view=request.nextUrl.searchParams.get("view"),cursor=request.nextUrl.searchParams.get("cursor");let query=view==="commissions"?db.collection("commissionLedger").orderBy("__name__").limit(31):db.collection("users").where("agentEnabled","==",true).orderBy("__name__").limit(31);if(cursor)query=query.startAfter(validId(cursor));const snapshot=await query.get(),docs=snapshot.docs.slice(0,30);const metrics=docs.length?await db.getAll(...docs.map(doc=>db.doc(`${view==="commissions"?"commissionStates":"agentMetrics"}/${doc.id}`))):[];return NextResponse.json({records:docs.map((doc,index)=>view==="commissions"?{id:doc.id,...doc.data(),...metrics[index]?.data()}:{id:doc.id,displayName:doc.data().displayName,...metrics[index]?.data()}),nextCursor:snapshot.size>30?docs[29].id:null});}catch(error){return failure(error);}}
export async function POST(request:NextRequest){try{const admin=await requireAdmin(request,"finance:adjust"),body=await request.json(),db=adminDb();
if(body.action==="configure"){if(admin.role!=="super_admin")throw new MarketplaceError("Super admin access required.",403);if(!Number.isFinite(body.commissionRate)||body.commissionRate<0||body.commissionRate>1)throw new MarketplaceError("Commission rate must be between 0 and 1.");await db.doc("marketplaceConfig/agents").set({commissionRate:body.commissionRate,updatedAt:FieldValue.serverTimestamp()},{merge:true});await writeAdminAuditLog(request,{admin,actionType:"commission.configure",newValue:{commissionRate:body.commissionRate},reason:"Updated rate for future commissions"});return NextResponse.json({success:true});}
const id=validId(body.id),status=body.status;if(!["available","paid","reversed"].includes(status))throw new MarketplaceError("Invalid commission transition.");const reason=String(body.reason??"").trim(),paymentReference=String(body.paymentReference??"").trim();if(!reason||status==="paid"&&!paymentReference)throw new MarketplaceError("A reason and, for payments, a payment reference are required.");
await db.runTransaction(async tx=>{const ledgerRef=db.doc(`commissionLedger/${id}`),stateRef=db.doc(`commissionStates/${id}`);const [ledgerSnap,stateSnap]=await Promise.all([tx.get(ledgerRef),tx.get(stateRef)]);if(!ledgerSnap.exists)throw new MarketplaceError("Commission not found.",404);const ledger=ledgerSnap.data()!,previous=String(stateSnap.data()?.status??"pending");if(previous===status)return;if(previous==="reversed"||status==="available"&&previous!=="pending"||status==="paid"&&previous!=="available")throw new MarketplaceError("This commission cannot make that transition.",409);tx.update(stateRef,{status,updatedAt:FieldValue.serverTimestamp(),...(status==="paid"?{paidAt:FieldValue.serverTimestamp(),paymentReference}:{})});tx.create(db.doc(`commissionEvents/${id}_${status}`),{commissionId:id,status,previous,adminId:admin.uid,reason,paymentReference:paymentReference||null,createdAt:FieldValue.serverTimestamp()});tx.set(db.doc(`agentMetrics/${ledger.agentId}`),{[`${previous}Commission`]:FieldValue.increment(-ledger.commissionAmount),[`${status}Commission`]:FieldValue.increment(ledger.commissionAmount),...(status==="reversed"?{earnedCommission:FieldValue.increment(-ledger.commissionAmount)}:{})},{merge:true});});await writeAdminAuditLog(request,{admin,actionType:`commission.${status}`,newValue:{id,status,paymentReference},reason});return NextResponse.json({success:true});}catch(error){return failure(error);}}
function failure(error:unknown){return NextResponse.json({error:error instanceof Error?error.message:"Agent administration failed."},{status:error instanceof MarketplaceError?error.status:adminErrorStatus(error)});}
