"use client";
import { useState } from "react";
import Link from "next/link";
import { AgentNavigation } from "@/components/profile/AgentNavigation";
import { useProtectedRoute } from "@/hooks/useProtectedRoute";
import { authenticatedJson,useOperationalData } from "@/hooks/useOperationalData";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { AcquisitionFunnel } from "@/components/admin/AcquisitionFunnel";
import { flatJobCategories } from "@/lib/jobCategories";
type AgentData={enabled:boolean;metrics:Record<string,number>;links:Array<{id:string;name:string}>};
export default function AgentPage(){
const {user,loading,isAuthorized,refreshProfile}=useProtectedRoute(),[error,setError]=useState(""),[busy,setBusy]=useState(false);const {data,error:loadError,refresh}=useOperationalData<AgentData>(user?"/api/agent":null);
async function send(body:Record<string,unknown>){if(!user)return;setBusy(true);setError("");try{await authenticatedJson("/api/agent",await user.getIdToken(),{method:"POST",body:JSON.stringify(body)});await refreshProfile();refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to update agent account.");}finally{setBusy(false);}}
if(loading||!isAuthorized)return <p role="status">Checking your account…</p>;
return <div className="mx-auto max-w-5xl space-y-5"><h1 className="text-3xl font-black">COPIC Agent</h1>{(error||loadError)&&<p role="alert" className="copic-error">{error||loadError}</p>}{!data&&!loadError&&<p role="status">Loading your agent dashboard…</p>}{data&&!data.enabled?<Card><h2 className="text-xl font-bold">Become a COPIC Agent</h2><p className="mt-3">Help new workers join COPIC. Earn commission on eligible completed work from your referrals. Keep using your existing client and worker modes.</p><Link className="recruitment-primary mt-4" href="/become-agent">Become a COPIC Agent</Link></Card>:data&&<><AgentNavigation/><div className="copic-marketplace-grid">{Object.entries({peopleReferred:"People referred",skill_added:"Workers with skills",id_verified:"Verified workers",first_completed_job:"Workers who completed jobs",earnedCommission:"Commission earned",pendingCommission:"Pending commission",availableCommission:"Available commission",paidCommission:"Paid commission"}).map(([key,label])=><Card key={key}><p className="copic-muted text-sm">{label}</p><p className="mt-2 text-3xl font-black">{key.includes("Commission")?"KSh ":""}{(data.metrics[key]??0).toLocaleString()}</p></Card>)}</div><Card><h2 className="text-xl font-bold">Your referral links</h2><form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();void send({action:"create_link",service:new FormData(event.currentTarget).get("service")||null});}}><label className="temp-label flex-1">Service (leave empty for a general link)<input name="service" list="agent-services" className="temp-input w-full p-3"/></label><datalist id="agent-services">{flatJobCategories.map(name=><option key={name}>{name}</option>)}</datalist><Button disabled={busy}>Create link</Button></form><div className="mt-4 space-y-3">{data.links.map(link=><div className="flex flex-wrap items-center justify-between gap-3" key={link.id}><Link className="recruitment-secondary break-all" href={`/join/${link.id}`}>{link.name}</Link><Button variant="secondary" onClick={()=>navigator.clipboard.writeText(`${location.origin}/join/${link.id}`).catch(()=>setError("Copy the referral link address."))}>Copy link</Button></div>)}{!data.links.length&&<p className="copic-muted">Create a link to start referring workers.</p>}</div></Card><AcquisitionFunnel data={data.metrics}/></>}</div>;
}
