"use client";
import { useState } from "react";
import Link from "next/link";
import { useProtectedRoute } from "@/hooks/useProtectedRoute";
import { useOperationalData } from "@/hooks/useOperationalData";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
type RecordRow={id:string;referredWorkerId?:string;serviceId?:string;jobId?:string;commissionAmount?:number;status?:string;paymentReference?:string};
export function AgentRecords({view}:{view:"referrals"|"earnings"}){const {user,isAuthorized}=useProtectedRoute(),[cursor,setCursor]=useState("");const {data,error}=useOperationalData<{enabled:boolean;records?:RecordRow[];nextCursor?:string|null}>(user?`/api/agent?view=${view}&cursor=${cursor}`:null);return <div className="mx-auto max-w-4xl space-y-4"><Link href="/agent" className="underline">Agent dashboard</Link><h1 className="text-3xl font-black">{view==="referrals"?"My referrals":"Commission ledger"}</h1>{error&&<p role="alert" className="copic-error">{error}</p>}{(!data||!isAuthorized)&&!error&&<p role="status">Loading…</p>}{data?.enabled===false&&<Card>Become a COPIC Agent to view referrals and earnings.</Card>}{data?.records?.length===0&&<Card>{view==="referrals"?"No referrals yet. Share your agent link to get started.":"No eligible commissions yet. Completed, confirmed worker payments will appear here."}</Card>}<div className="copic-marketplace-grid">{data?.records?.map(row=><Card key={row.id}>{view==="referrals"?<><h2 className="font-bold break-all">Worker {row.referredWorkerId}</h2><p className="mt-2 copic-muted">{row.serviceId?decodeURIComponent(row.serviceId):"General referral"}</p></>:<><p className="text-2xl font-black">KSh {row.commissionAmount?.toFixed(2)}</p><p className="mt-2 font-bold capitalize">{row.status}</p><p className="mt-2 break-all copic-muted">Job {row.jobId}</p>{row.paymentReference&&<p className="mt-2 break-all">Payment: {row.paymentReference}</p>}</>}</Card>)}</div><div className="flex gap-3">{cursor&&<Button onClick={()=>setCursor("")}>First page</Button>}{data?.nextCursor&&<Button onClick={()=>setCursor(data.nextCursor!)}>Next page</Button>}</div></div>;}
