"use client";
import { useEffect,useState,useCallback } from "react";
import Link from "next/link";
import { useAuth } from "@/context/AuthContext";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { IdentityVerificationModal } from "@/components/verification/IdentityVerificationModal";
import { AddSkillModal } from "@/components/profile/AddSkillModal";
type LinkData={name:string;service:string|null;rate:number|null;unit:string|null;targetLocation:string|null};
export function RecruitmentLanding({id,type}:{id:string;type:"admin_campaign"|"agent_referral"}) {
  const {user,profile,refreshProfile}=useAuth(),[link,setLink]=useState<LinkData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[added,setAdded]=useState(false),[verify,setVerify]=useState(false),[submitted,setSubmitted]=useState(false),[skillModal,setSkillModal]=useState(false),[attached,setAttached]=useState(false);
  const endpoint=`/api/acquisition?id=${encodeURIComponent(id)}&type=${type}`;
  const action=useCallback(async(name:string)=>{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json",...(user?{Authorization:`Bearer ${await user.getIdToken()}`}:{})},body:JSON.stringify({action:name})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to continue.");return data;},[endpoint,user]);
  useEffect(()=>{let stopped=false;fetch(endpoint).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);if(!stopped)setLink(data.link);}).catch(reason=>!stopped&&setError(reason.message));return()=>{stopped=true;};},[endpoint]);
  useEffect(()=>{if(!link)return;window.sessionStorage.setItem("copic.acquisition.return",`/${type==="admin_campaign"?"recruit":"join"}/${id}`);let stopped=false;void action("link_clicked").then(async()=>{if(user&&profile){await action("attach");if(!stopped)setAttached(true);}}).catch(reason=>!stopped&&setError(reason.message));return()=>{stopped=true;};},[link,id,type,user,profile,action]);
  return <div className="mx-auto max-w-2xl space-y-5 py-6"><p className="copic-eyebrow">COPIC · {link?.targetLocation??"Flexible work"}</p><h1 className="text-3xl font-black">{link?.service?`We're looking for ${link.service.toLowerCase()} workers`:"Find your next opportunity on COPIC"}</h1>{!link&&!error&&<p role="status">Loading recruitment details…</p>}{error&&<p role="alert" className="copic-error">{error}</p>}{link&&<Card>{link.rate&&<h2 className="text-2xl font-bold">Earn KSh {link.rate} per {link.unit}</h2>}<p className="mt-3 copic-muted">Clients looking for {link.service??"your services"} will be able to find you on COPIC.</p><p className="mt-3">Know someone who does this? Forward this link to them.</p>
  {!user?<><p className="mt-5">Create your free COPIC account to continue. It only takes a minute.</p><Link className="mt-4 inline-flex min-h-11 items-center font-bold underline" href="/auth/register" onClick={()=>void action("signup_started").catch(()=>undefined)}>Apply{link.service?` as a ${link.service} worker`:" to COPIC"}</Link><Link className="ml-4 inline-flex min-h-11 items-center underline" href="/auth/login">Sign in</Link></>:!profile?<Link className="mt-5 inline-flex min-h-11 items-center font-bold underline" href="/complete-profile">Complete your free account</Link>:!added?<Button className="mt-5" disabled={busy||(!attached&&type==="admin_campaign")} onClick={async()=>{setBusy(true);setError("");try{if(type==="admin_campaign"){await action("add_skill");await refreshProfile();setAdded(true);}else{await action("enable_worker");await refreshProfile();setSkillModal(true);}}catch(reason){setError(reason instanceof Error?reason.message:"Unable to add service.");}finally{setBusy(false);}}}>{busy?"Adding service…":`Add ${link.service??"a service"} to my profile`}</Button>:<><h2 className="mt-5 text-xl font-bold">{submitted?"You're in!":"One last step — verify your identity."}</h2><p className="mt-3">{submitted?"Your service is now visible on COPIC. We'll let you know when you're ready to accept work.":"Verification helps clients know they're hiring a real person. Your service is visible, and requests will stay saved while you verify."}</p>{!submitted&&<Button className="mt-4" onClick={()=>{void action("id_verification_started").catch(()=>undefined);setVerify(true);}}>Verify my ID</Button>}<Link className="mt-4 block underline" href="/profile" onClick={()=>sessionStorage.removeItem("copic.acquisition.return")}>Open my profile</Link></>}
  </Card>}{verify&&profile&&<IdentityVerificationModal profile={profile} onClose={()=>setVerify(false)} onSubmitted={async()=>{setSubmitted(true);setVerify(false);sessionStorage.removeItem("copic.acquisition.return");await refreshProfile();}}/>}{skillModal&&profile&&<AddSkillModal initialName={link?.service??undefined} onClose={()=>setSkillModal(false)} onSaved={async()=>{setSkillModal(false);setAdded(true);await refreshProfile();}}/>}</div>;
}
