import "./fixtures";
import { Suspense } from "react";
import { createRoot } from "react-dom/client";
import AdminLayout from "@/app/admin/layout";
import Overview from "@/app/admin/page";
import Skills from "@/app/admin/skills/page";
import Recruitment from "@/app/admin/recruitment/page";
import Campaign from "@/app/admin/recruitment/[campaignId]/page";
import Agents from "@/app/admin/agents/page";
import Analytics from "@/app/admin/analytics/page";
import Verification from "@/app/admin/kyc/page";
import Jobs from "@/app/admin/jobs/page";
import Users from "@/app/admin/users/page";
import Agent from "@/app/agent/page";
import { AgentRecords } from "@/components/profile/AgentRecords";
import { RecruitmentLanding } from "@/components/profile/RecruitmentLanding";
import { ConnectionStatus } from "@/components/layout/ConnectionStatus";
import MarketplaceMap from "@/components/admin/MarketplaceMap";
const campaignParams=Promise.resolve({campaignId:"campaign-demo"});
const pages:Record<string,React.ReactNode>={"/admin":<Overview/>,"/admin/skills":<Skills/>,"/admin/recruitment":<Recruitment/>,"/admin/recruitment/campaign-demo":<Campaign params={campaignParams}/>,"/admin/agents":<Agents/>,"/admin/analytics":<Analytics/>,"/admin/verification":<Verification/>,"/admin/kyc":<Verification/>,"/admin/jobs":<Jobs/>,"/admin/users":<Users/>,"/admin/map":<MarketplaceMap/>,"/agent":<Agent/>,"/agent/referrals":<AgentRecords view="referrals"/>,"/agent/earnings":<AgentRecords view="earnings"/>,"/recruit/campaign-demo":<RecruitmentLanding id="campaign-demo" type="admin_campaign"/>,"/join/agent-link":<RecruitmentLanding id="agent-link" type="agent_referral"/>};
const theme=new URLSearchParams(location.search).get("theme")??"light";
document.documentElement.dataset.uiTheme=theme;
const page=pages[location.pathname]??<p>Choose a fixture route.</p>;
createRoot(document.getElementById("root")!).render(<><ConnectionStatus/><div style={{padding:16,maxWidth:1440,margin:"0 auto",width:"100%"}}><Suspense fallback={<p>Loading UI fixture…</p>}>{location.pathname.startsWith("/admin")?<AdminLayout>{page}</AdminLayout>:page}</Suspense></div></>);
