"use client";
import Map, { Source, Layer, NavigationControl, type MapRef } from "react-map-gl/mapbox";
import { useEffect, useRef, useState } from "react";
import { useOperationalData } from "@/hooks/useOperationalData";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { defaultKenyaLocation } from "@/lib/location";
type MapData = { markers: Array<{ id: string; latitude: number; longitude: number; users: number }>; totals: Record<string, number>; cellSize: number };
export default function MarketplaceMap() {
  const map = useRef<MapRef>(null), timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const [bounds, setBounds] = useState(""), [role, setRole] = useState("all"), [verified, setVerified] = useState("all"), [skillState, setSkillState] = useState("all"), [skill, setSkill] = useState(""), [dark, setDark] = useState(false);
  const [locationError, setLocationError] = useState("");
  const { data, error, loading } = useOperationalData<MapData>(bounds ? `/api/admin/marketplace?view=map&${bounds}&role=${role}&verified=${verified}&skillState=${skillState}&skill=${encodeURIComponent(skill)}` : null, 60000);
  useEffect(() => {
    void import("mapbox-gl/dist/mapbox-gl.css");
    const sync = () => setDark(document.documentElement.dataset.uiTheme === "dark"); sync();
    const observer = new MutationObserver(sync); observer.observe(document.documentElement, { attributes: true, attributeFilter: ["data-ui-theme"] });
    return () => { observer.disconnect(); clearTimeout(timer.current); };
  }, []);
  const updateBounds = () => { clearTimeout(timer.current); timer.current = setTimeout(() => { const b = map.current?.getBounds(); if (b) setBounds(`west=${Math.max(-180,b.getWest())}&east=${Math.min(180,b.getEast())}&south=${Math.max(-90,b.getSouth())}&north=${Math.min(90,b.getNorth())}`); }, 350); };
  const token = process.env.NEXT_PUBLIC_MAPBOX_TOKEN;
  if (!token) return <Card>The map needs the existing NEXT_PUBLIC_MAPBOX_TOKEN configuration.</Card>;
  return <div className="space-y-4">
    <form className="flex flex-wrap gap-3" onSubmit={async event => { event.preventDefault(); setLocationError(""); const area = String(new FormData(event.currentTarget).get("area") ?? ""); try { const response = await fetch(`https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(area)}.json?access_token=${encodeURIComponent(token)}&limit=1`); if (!response.ok) throw new Error("Location search unavailable."); const payload = await response.json(); const center = payload.features?.[0]?.center; if (!center) throw new Error("Area not found."); map.current?.flyTo({ center, zoom: 12 }); } catch(reason) { setLocationError(reason instanceof Error ? reason.message : "Area not found."); } }}><label className="temp-label flex-1">Location / area<input name="area" required className="temp-input w-full p-3" placeholder="Find an area or city" /></label><Button>Find area</Button></form>
    <div className="copic-marketplace-grid">{[{ label: "User type", value: role, set: setRole, options: ["all", "worker", "client"] }, { label: "Identity", value: verified, set: setVerified, options: ["all", "verified", "unverified"] }, { label: "Worker skills", value: skillState, set: setSkillState, options: ["all", "with", "without"] }].map(filter => <label className="temp-label" key={filter.label}>{filter.label}<select className="temp-input w-full p-3" value={filter.value} onChange={event => filter.set(event.target.value)}>{filter.options.map(value => <option key={value}>{value}</option>)}</select></label>)}<form onSubmit={event => { event.preventDefault(); setSkill(String(new FormData(event.currentTarget).get("skill") ?? "")); }}><label className="temp-label">Exact service<input name="skill" className="temp-input w-full p-3" placeholder="All services" /></label><Button className="mt-2" variant="secondary">Filter service</Button></form></div>
    {(error || locationError) && <p role="alert" className="copic-error">{error || locationError}</p>}
    <div className="overflow-hidden rounded-2xl border" style={{ height: "min(60vh, 520px)", borderColor: "var(--border)" }}><Map ref={map} mapboxAccessToken={token} initialViewState={{ latitude: defaultKenyaLocation.latitude, longitude: defaultKenyaLocation.longitude, zoom: 10 }} onLoad={updateBounds} onMoveEnd={updateBounds} mapStyle={dark ? "mapbox://styles/mapbox/dark-v11" : "mapbox://styles/mapbox/light-v11"} onError={() => setLocationError("Map could not load. Check your connection and map configuration.")}><NavigationControl /><Source id="supply" type="geojson" data={{ type: "FeatureCollection", features: (data?.markers ?? []).map(item => ({ type: "Feature", properties: { count: item.users }, geometry: { type: "Point", coordinates: [item.longitude, item.latitude] } })) }}><Layer id="supply-circles" type="circle" paint={{ "circle-color": "#b2f746", "circle-radius": ["interpolate", ["linear"], ["get", "count"], 1, 12, 100, 24, 1000, 36], "circle-opacity": 0.8 }} /><Layer id="supply-labels" type="symbol" layout={{ "text-field": ["to-string", ["get", "count"]], "text-size": 12 }} paint={{ "text-color": "#191c1d" }} /></Source></Map></div>
    {loading && <p role="status">Loading area counts…</p>}{data && <><p className="copic-muted text-sm">Grid size: {data.cellSize}°. Counts include cell edges. Worker and client capabilities can overlap.</p><div className="copic-marketplace-grid">{Object.entries({ users: "Total users", workers: "Workers", clients: "Clients", workersWithSkills: "Workers with skills", workersWithoutSkills: "Workers without skills", verifiedWorkers: "Verified workers", unverifiedWorkers: "Unverified workers" }).map(([key,label]) => <Card key={key}><p className="copic-muted">{label}</p><p className="text-3xl font-black">{data.totals[key] ?? 0}</p></Card>)}</div><Card><h2 className="text-xl font-bold">Services in this area</h2>{Object.entries(data.totals).filter(([key]) => key.startsWith("service:")).sort((a,b) => b[1]-a[1]).map(([key,count]) => <p className="mt-2" key={key}>{decodeURIComponent(key.slice(8))} — {count}</p>)}{!data.markers.length && <p className="mt-3">No indexed supply matches this area and filters.</p>}</Card></>}
  </div>;
}
